### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by slossgaming** [sentanos/roblox-js-server#12]
Make it so we can get a players blurb.

**Comment by slossgaming** [comment]
Can you add this feature, it would help me a ton!

**Comment by sentanos** [comment]
I will look into adding it in a minor release soon.

**Comment by slossgaming** [comment]
Okay, If you thank you.

**Comment by sentanos** [comment]
Added in v1.2.0, please follow instructions in [updating](https://github.com/sentanos/roblox-js-server#updating) (both server files and dependencies) to add the feature to your server.
