### ISSUE TITLE
Ruby.exe is not recognized as an internal or external command

### ISSUE THREAD

**Issue by YouFoundJojo** [sentanos/roblox-js-server#13]
I downloaded the Heroku Toolbelt, and did the `cd C:\Users\YouFoundJojo\Desktop\roblox-js-server-master` command, and then I hit enter. So far, everything was working.

I typed in `heroku login`, and it gave me an error saying 

> 'ruby.exe' is not recognized as an internal or external command,
operable program or batch file.

Help? @sentanos

**Comment by slossgaming** [comment]
Contact me via skype and i'l help. MatthewWalden11

**Comment by YouFoundJojo** [comment]
Sent request.

**Comment by YouFoundJojo** [comment]
I still need help- can someone help me? @sentanos

**Comment by YouFoundJojo** [comment]
Also, could someone potentially explain how to execute commands after getting the link to the heroku server (using the module provided in the lua folder)

**Comment by sentanos** [comment]
Did the installer run through successfully?

**Comment by YouFoundJojo** [comment]
Yes, it successfully installed Git and the Heroku Toolbelt- I installed Ruby to see if that would fix it but I don't know where to extract it in my computer.

**Comment by sentanos** [comment]
Try to run the installer [here](https://rubyinstaller.org) and try again. If it still doesn't work, try to reinstall heroku command line tools again.

**Comment by YouFoundJojo** [comment]
Thanks- your solution worked!
