### ISSUE TITLE
A bit of confusion

### ISSUE THREAD

**Issue by conman0552** [sentanos/roblox-js-server#14]
I had a question about everything regarding running it from a roblox server. I set everything up, added the key, username, and password, and all that, However I was confused as to how I run it in roblox. My original understanding was it would come out to be api.shout(groupId, "Test") but that has proved useless. I took a closer look and still came up with no solution, and your example didn't help me very well either. What is a Json format also. Could you maybe mark this out for future users so they know how to exucute these things in an LUA script?

**Comment by sentanos** [comment]
As it says if you initialized api with the groupId argument all group-related functions will automatically use that ID (so if you did you would only do something like `api.shout'Test'`). If you do not initialize api with the groupId then you would do it the way you were saying. For JSON there are plenty of [resources](http://lmgtfy.com/?q=json+tutorial) online, but if you are using the module you don't have to worry about it because it encodes everything for you.

**Comment by conman0552** [comment]
Oh, I did Initialize api with the groupId argument, as I said, I looked in closer and tried other things, after realizing api.shout(groupId) was irrelivent as I already defined the groupID in the api. I did just try the api.shout'Test' It showed no errors in the script and seemed promising, however it still did not work. Could you maybe just give me an example of how someone would normally shout something from a script? That might clarify what I was doing wrong, I am not very confused now, but I just don't understand what I have to do to run the code and post a shout.

**Comment by sentanos** [comment]
Just take the lua example and have everything at the top but change the api calls to api.shout. Could you please show me the script that isn't working for you? Otherwise it is very hard for me to identify your problem.

**Comment by conman0552** [comment]
Alright. game.Players.PlayerAdded:connect(function(nP)
	nP.Chatted:connect(function(message)
		for _, p in pairs(prefixes) do
			if string.lower(message) == p.."corview online" then
				if nP:GetRankInGroup(TRoA) >= 249 then
					createAudit(nP, message)
					MEvent:FireAllClients("Corview was just enabled! The AutoXP System has been enabled! Every 10 minutes 5 XP will be given!")
					corview_online = true
					WebHook:post{
					username = "TRoA Training Bot",
					content = "TEST FOR TROA CORVIEW SYSTEMS"
					}
					api.shout("test")
				end
			end
		end
	end)
end)
I have the top as this

local server = require(Rep.Modules.Server)
local domain = 'troa-server.herokuapp.com' -- Make sure there is no http:// in here!
local key = 'x3745V37'
local userId = game:GetService'Players':GetUserIdFromNameAsync'conman0552'
local groupId = 2928417
local api = server(domain, key, groupId)

(Normally I wouldn't give that part, seeing as it contains the key and domain of the site, but I'll do it for this)

**Comment by sentanos** [comment]
You do not have to leave the key or domain in, I would change it later. Could you please change the shout line to `print(api.shout("test").message)` and tell me the output.

**Comment by conman0552** [comment]
Http 502 (HTTP/1.1 503 Service Unavailable)
Stack Begin 
Script 'ReplicatedStorage.Modules.Server' Line 21 - upvalue post
Script 'ReplicatedStorage.Modules.Server' Line 40 - upvalue http
Script 'ReplicatedStorage.Modules.Server' Line 56 - upvalue func
Script 'ReplicatedStorage.Modules.Server' Line 116 - field shout
Script 'ServerScriptStorage.Core', line 348
Stack End

**Comment by sentanos** [comment]
There is a problem with your server setup, please do the following:
1. Go to the app logs (in your case this would be located at [https://dashboard.heroku.com/apps/troa-server/logs](https://dashboard.heroku.com/apps/troa-server/logs))
2. Click "More" in the top right corner and then "Restart all dynos"
3. Take a screenshot of the logs and post it here

**Comment by conman0552** [comment]
![image](https://cloud.githubusercontent.com/assets/24281023/22005257/40e4c0e2-dc27-11e6-8e64-7b3828c7497e.png)
![image](https://cloud.githubusercontent.com/assets/24281023/22005258/46d4ba70-dc27-11e6-9ae1-5872cd391a04.png)
![image](https://cloud.githubusercontent.com/assets/24281023/22005262/4e2e0f42-dc27-11e6-8bf6-a6d4c3aa79d6.png)
![image](https://cloud.githubusercontent.com/assets/24281023/22005268/57e35d76-dc27-11e6-8e33-e175fe7db586.png)

**Comment by sentanos** [comment]
It looks like the setup of your settings.json is wrong, do you have all the parameters correctly wrapped in quotes?

**Comment by conman0552** [comment]
Yes I do, every value and key is in quotes except for the number value for maximumrank are in quotes

**Comment by sentanos** [comment]
Could you please post your settings.json with the username/password/token changed.

**Comment by conman0552** [comment]
Yes,
{
  "username": "REDACTED",
  "password":"REDACTED",
  "key": "x3745V37",
  "maximumRank": 250
}

**Comment by sentanos** [comment]
Could you tell me what character is at position 66 in your regular settings.json? (Character #66)? Because it is causing a problem and I can't see what without seeing the entire thing.

**Comment by conman0552** [comment]
it is , it is right after "password":"REDACTED"

**Comment by sentanos** [comment]
Could you open your text editor, change out the username and password as you did above, and take a screenshot?

**Comment by conman0552** [comment]
Yes
![image](https://cloud.githubusercontent.com/assets/24281023/22005558/ee6ea956-dc29-11e6-9a08-afc9674d92bb.png)

**Comment by sentanos** [comment]
Does the password contain any quotes or special characters in it?

**Comment by conman0552** [comment]
Uh, no, the username does however. it is a _

**Comment by sentanos** [comment]
Put your settings.json file in the same format as it was originally (copy and paste [this](https://raw.githubusercontent.com/sentanos/roblox-js-server/master/settings.json) and put the info back in) and then update your server by following steps 4, 6, and 7 of the updating section.

**Comment by conman0552** [comment]
I just attempted to update it, 
![image](https://cloud.githubusercontent.com/assets/24281023/22005732/409fe388-dc2b-11e6-9afa-f854cff04720.png)
I got to step 6 and that happened.

**Comment by sentanos** [comment]
Something is completely wrong with your setup, please carefully set up a new server.

**Comment by conman0552** [comment]
Alright, I will.

**Comment by conman0552** [comment]
Alright, I just set up a new server, I will test it now, and see what happens.

**Comment by conman0552** [comment]
It works! Thank you so much! I appreciate the help.
