### ISSUE TITLE
database.doPost(sheet, key, id) is not working.

### ISSUE THREAD

**Issue by Dev-Otmas** [sentanos/roblox-js-server#15]
Whenever I try to run `database.doPost(GlobalDb, ID, Rank)`, I get the error `ServerScriptService.DatabaseManagement:28 attempt to call method "doPost" (a nil value)`
The full text of my code is this:
print("DatabaseManagement Online, created by conman0552")
--Localized-Variables--
--Rank points--
local Outlaw = 1
local Trainees = 10
local Agents = 25
local Coverts = 50
local Specialists = 65
local Trooper = 80
local Sentinel = 95
local Legionnaire = 100
local Captain = 130
local Officer = 300
------------
--Other Variables--
database = require(game.ReplicatedStorage.Modules.DatabaseService);
TRoA = 2928417
globalDb = database:GetDatabase("Global")
banDb = database:GetDatabase("Bans")
xpDb = database:GetDatabase("XP")
-------------------
--Everything below can be broken if modified too much, be careful
--Rank checking awesomeness--
game.Players.PlayerAdded:connect(function(nP)
	local Rank = nP:GetRoleInGroup(TRoA)
	local ID = nP.UserId
		print(xpDb, ID)
		database.doPost(xpDb, ID, Rank)
		local test = Instance.new("Hint")
		test.Text = ("We called the function right!")
		test.Parent = workspace
end)
function banPlr(player)
	banDb:PostAsync(player, "Banned!")
end

**Comment by Dev-Otmas** [comment]
Dear God markdown screwed that up...

**Comment by sentanos** [comment]
Wait...what the heck does this have to do with the project?

**Comment by Dev-Otmas** [comment]
Wait, wrong API, sorry
