### ISSUE TITLE
Error is incorrectly thrown when using "setRank"

### ISSUE THREAD

**Issue by notPeasant** [sentanos/roblox-js-server#18]
Hi, the following error is thrown when using "setRank" from the Lua api.
js-server:27: Set rank failed: name is not defined
But the rank change is successful on the website. Would you mind taking a look as to what might've caused this error? 
I've determined this error is caused from the server because when printing "body", it says the same error.
![image](https://cloud.githubusercontent.com/assets/17164805/22135401/256e7e82-de8b-11e6-886e-188925d4c92b.png)

Thanks.

**Comment by sentanos** [comment]
Interesting, please provide the following information:
Name of the user you are changing the rank of
Rank you were changing them to
Name of the rank you were changing them to (or just link the related group)

**Comment by notPeasant** [comment]
Here is the call I made:
api.setRank(854166, 179010137, 10)

I had to modify the function in the api to the following:
![image](https://cloud.githubusercontent.com/assets/17164805/22135442/5b62a428-de8b-11e6-92d7-768e8668d756.png)

Otherwise, the group argument was passed twice:
![image](https://cloud.githubusercontent.com/assets/17164805/22135479/abb2bd46-de8b-11e6-93ec-6de5eacc0cfe.png)
![image](https://cloud.githubusercontent.com/assets/17164805/22135470/97cc05b2-de8b-11e6-93b2-edaa085e1cd5.png)

**Comment by sentanos** [comment]
Wait, why did you make that modification?

**Comment by notPeasant** [comment]
The second set of pictures. Kept saying Rank <Huge number> is above the rank limit.

**Comment by sentanos** [comment]
You were using the api incorrectly. Remember, if you call the api with the group argument it will automatically be appended to all functions. Otherwise you have to put it in.

**Comment by sentanos** [comment]
As for the name error I'll have to look into it more I'm not very sure what would cause that.

**Comment by notPeasant** [comment]
That makes sense.

Thanks for looking into this :)

**Comment by sentanos** [comment]
Where have you set this server up?

**Comment by notPeasant** [comment]
Heroku, I followed the "Free Host Tutorial"

**Comment by sentanos** [comment]
And you can confirm you are still receiving it and that that line is what's causing it? It just doesn't make sense to me why that error would appear even though the rank change is still going through.

**Comment by notPeasant** [comment]
Yes,
Users current rank:
![image](https://cloud.githubusercontent.com/assets/17164805/22136016/f9a21dd2-de8e-11e6-8e36-d928f6361967.png)
![image](https://cloud.githubusercontent.com/assets/17164805/22136006/ee16eca4-de8e-11e6-8377-9c6b91c0584c.png)

Request:
![image](https://cloud.githubusercontent.com/assets/17164805/22136018/020bf74a-de8f-11e6-9bbc-d7a864a54eb6.png)
User's rank changed:
![image](https://cloud.githubusercontent.com/assets/17164805/22136034/167544fc-de8f-11e6-9dd0-ca3ec8c8ec0a.png)

Error still present:
![image](https://cloud.githubusercontent.com/assets/17164805/22136047/2d5ebcf2-de8f-11e6-961f-b057019a055b.png)

**Comment by sentanos** [comment]
I cannot reproduce your error, [update](https://github.com/sentanos/roblox-js-server#updating) to the newest version and try again.
