### ISSUE TITLE
Too long of a shout?

### ISSUE THREAD

**Issue by conman0552** [sentanos/roblox-js-server#20]
I got my shout system working for the most part, but I found a slight error. It shouts when I do api.shout("test") or something like api.shout("Isn't this really cool?") however, when I try to do something like api.shout("[TRAIN] Training is being held at Corview! https://www.roblox.com/games/563411782/Demo-1TRoA-training-facility#") does not work. I have taken the message and copied it into the shout area, and there is about 120 characters to spare. Does this not post anything with a URL in it? or is it too long? I don't know why this is happening, and the errors I get on the f9 console when I try to do api.shout("[TRAIN] Training is being held at Corview! https://www.roblox.com/games/563411782/Demo-1TRoA-training-facility#") are Something along the lines of "Error shouting, check your key, permissions, message, ect" However the other 2 do not error at all, the code code works.

**Comment by sentanos** [comment]
Interesting, I will investigate with that message.

**Comment by conman0552** [comment]
Thanks, I don't know why it does that, but if you come up with anything please tell me, as I need that to be the message it shouts.

**Comment by sentanos** [comment]
The problem likely has to do with the way the server escaped inputs, as I have confirmed it is not a problem with the core module.

**Comment by conman0552** [comment]
What do you mean the server escape inputs? Is there any way to fix this?

**Comment by sentanos** [comment]
Yes, I will push a fix soon.

**Comment by conman0552** [comment]
Thanks! I'll be sure to update it.

**Comment by sentanos** [comment]
Updated to v1.2.0, please [update your server files](https://github.com/sentanos/roblox-js-server#updating) and confirm that the bug has been fixed.

**Comment by conman0552** [comment]
I updated them, it works. Thank you so much, I appreciate it!
