### ISSUE TITLE
Internal Server Error when trying to use blurb

### ISSUE THREAD

**Issue by slixxed** [sentanos/roblox-js-server#22]

**Comment by sentanos** [comment]
- Who's blurb?
- How are you calling it

**Comment by slixxed** [comment]
19:15:52.162 - Workspace.Script.MainModule:37: Internal server error

local server = require(script.MainModule)
local domain = 'myapp.herokuapp.com' -- Make sure there is no http:// in here!
local key = 'mykey' -- changed the domain and key for github issues
local groupId = 2839176
local api = server(domain, key, groupId)

print(api.getBlurb(1).data.blurb)

tried changing things like the way the blurb was called and the id, same issue, message and pretty much everything else works.

**Comment by sentanos** [comment]
Did you just install your server recently or have you had it running before and are just using getBlurb now?

**Comment by slixxed** [comment]
had it running, just updated it a few minutes ago.

**Comment by sentanos** [comment]
Please follow the second step of instructions here to update your dependencies https://github.com/sentanos/roblox-js-server#updating

**Comment by slixxed** [comment]
Oh that fixed it.. I feel dumb.. I thought that I wouldn't need to do that since It's only been a few days, rip... Thanks!
