### ISSUE TITLE
Incorrect Authentication Key

### ISSUE THREAD

**Issue by mccrafter1212** [sentanos/roblox-js-server#24]
Well, it seems I'm having an issue which I can't fix. I get the following error:
18:33:58.068 - ServerScriptService.Server:72: Incorrect authentication key
18:33:58.069 - Stack Begin
18:33:58.070 - Script 'ServerScriptService.Server', Line 72 - upvalue request
18:33:58.070 - Script 'ServerScriptService.Server', Line 91 - field post
18:33:58.071 - Script 'ServerScriptService.Server', Line 105 - upvalue func
18:33:58.071 - Script 'ServerScriptService.Server', Line 223 - field promote
18:33:58.071 - Script 'ServerScriptService.Promotion', Line 9

Obviously this is all caused from me inputting the wrong auth key, although where do I get that auth key from? In your example you posted this script:

local server = require(script.Parent.Server)
local domain = 'roblox-json-server.herokuapp.com' -- Make sure there is no http:// in here!
local key = 'awdamwdkawdkajwdkawjdkhvkshdfkajkw' -- This is the key I used inside of settings.json
local groupId = 3088241
local userId = game:GetService'Players':GetUserIdFromNameAsync'BowlOfSushi'
local api = server(domain, key, groupId)
print(api.promote(userId).message)
print(api.message(userId, 'Subject', 'Body').message)
print(api.getBlurb(1).data.blurb)

Am I supposed to use the key I inputted in settings.json, or did I miss a step and the key is coming from somewhere else? Please help, it's appreciated!!

Also, I don't have roblox-js installed. Is that required?

Here's my exact code image:
http://prntscr.com/e5v7q6

**Comment by sentanos** [comment]
Please take a screenshot of your settings.json file (after removing username and password).

**Comment by mccrafter1212** [comment]
Here:

http://prntscr.com/e5vps1

**Comment by sentanos** [comment]
The files look correct, did you possibly have some trouble during the setup? It looks like the key wasn't uploaded to the server. Please redo the setup process completely (delete all existing files and follow the steps again) and tell me if you still have this problem.

**Comment by mccrafter1212** [comment]
Well, is roblox-js required? I didn't install that.

**Comment by sentanos** [comment]
If you are using heroku it is all handled automatically and you don't have to worry about it. Just follow the steps and it should work.

**Comment by mccrafter1212** [comment]
Should I be getting this after doing git add --all:

http://prntscr.com/e5vxxt

??
