### ISSUE TITLE
Receiving an error when attempting to promote

### ISSUE THREAD

**Issue by The-Tarkol** [sentanos/roblox-js-server#26]
This was all working perfectly, however since I checked this morning I am receiving an error when trying to connect to the site. Is this a roblox issue or did I mess up? The error is:
{"error":"Server configuration error: NotFound"}

Here's a screenshot if that would help: https://gyazo.com/1b580ec945d623dd5719f272d0a3f35f

**Comment by sentanos** [comment]
Please see here: https://github.com/sentanos/roblox-js/issues/18
