### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by BottyRBLX** [sentanos/roblox-js-server#28]
Hi, it worked previously but then it doesn't work anymore...? It's using the exact same thing as before but now it doesn't work.

**Comment by sentanos** [comment]
ROBLOX recently broke the library which I did patch. Please update your dependencies by following the instructions after "Sometimes you also have to update dependency files like roblox-js which the module requires" in the [updating](https://github.com/sentanos/roblox-js-server#updating) section.
