### ISSUE TITLE
Error sending message: "Message failed: Captcha"

### ISSUE THREAD

**Issue by BreadyToCrumble** [sentanos/roblox-js-server#31]
I send a message using the API, and it returns this:

https://gyazo.com/10ce207e7766197d54dbbd161acddc0a

This has never been an issue before. Nothing's changed.

**Comment by BreadyToCrumble** [comment]
Noticed that you sent out a patch the other day for a roblox library edit. Updating dependencies first.

**Comment by BreadyToCrumble** [comment]
I'm in contact with a few others who use your API, they're having the same issue.

**Comment by sentanos** [comment]
This doesn't sound like an issue with the module, this is simply ROBLOX forcing you to do a captcha challenge either during login or when you are making the message. There is no way to circumvent this other than actually solving the captcha (and to do that with the module is difficult).

**Comment by BreadyToCrumble** [comment]
So how would I go about fixing this? Would it be easier to make another account and set it up under that?

**Comment by sentanos** [comment]
You wouldn't. Botting messages simply isn't practical anymore.

Ok fine if you can find an old enough account you may be able to do it without this error because it seems like verified accounts made before a certain date are not given captcha challenges.

**Comment by BreadyToCrumble** [comment]
Well that's not very useful of Roblox. I'll have to figure out a different way to verify someone's Roblox account without asking for their password.

**Comment by BreadyToCrumble** [comment]
Thanks for the help.

**Comment by teddymisty132** [comment]
I figured out that you just need to verify the email of the bot and change the settings to allow all messages to everyone.
