### ISSUE TITLE
CURL error

### ISSUE THREAD

**Issue by conman0552** [sentanos/roblox-js-server#36]
I've been helping a friend of mine set up his own server to run this, and we came across this error. At a quick glace I didn't find anything on as to what it was. We have verified that the password is correct and the domain. This is our error: https://gyazo.com/16db20eeda790ab52cbed87ac4f99f7a

**Comment by sentanos** [comment]
Where are you setting up the server? Is it set up on heroku?

**Comment by conman0552** [comment]
It is on heroku.

**Comment by sentanos** [comment]
Ok, please refer to my first few responses on #33

**Comment by sentanos** [comment]
Are you still getting this error when running on a server as opposed to through ROBLOX Studio?

**Comment by conman0552** [comment]
It is coming on the server.

**Comment by sentanos** [comment]
Please post the code of the script you are using it with (without the key).

**Comment by sentanos** [comment]
What was the issue?
