### ISSUE TITLE
Auto Promote Issue

### ISSUE THREAD

**Issue by WolfieTheDino** [sentanos/roblox-js-server#39]
Hi i have a command like this

> game.Players.PlayerAdded:connect(function(nP)
	nP.Chatted:connect(function(message)
			if message:sub(1,8) == prefix.."Promote" then
				if nP:GetRankInGroup(3175977) >= 249 then
				local id = game:GetService'Players':GetUserIdFromNameAsync(message:sub(9))
				print(api.promote(id).message)
			end
			end
end)
end)

> 

and then it comes up with a error like

> 
12:55:34.085 - Players:GetUserIdFromName() failed because the user does not exist
12:55:34.086 - Stack Begin
12:55:34.087 - Script 'ServerScriptService.Webserver', Line 39
12:55:34.088 - Stack End

>

**Comment by sentanos** [comment]
That's an error from your script because the user does not exist, it literally has nothing to do with the module.
