### ISSUE TITLE
Heroku is not a valid command

### ISSUE THREAD

**Issue by nestenes** [sentanos/roblox-js-server#40]
Hi,

I get the error heroku is not a recognised internal or external command.
I did what you said in the instructions about dragging the folder in but still doesn't work.

**Comment by sentanos** [comment]
Make sure you have installed Heroku command line tools successfully as outlined in the instructions.

**Comment by nestenes** [comment]
Issue fixed.  I installed it using Windows UAC on a non-admin account therefore installing onto that admin account only, not what I intended for it to install on.
I had to be logged into that account instead for the commands to work.
