### ISSUE TITLE
Command prompt error

### ISSUE THREAD

**Issue by deathxrose** [sentanos/roblox-js-server#41]
I'm typing heroku login username password and it says heroku is not a command?

**Comment by deathxrose** [comment]
This is what happens if i try to open server 
![snipsls](https://user-images.githubusercontent.com/19968356/28036484-a3e7c1c6-6575-11e7-9b43-d59e8cfe7cc6.PNG)

**Comment by slossgaming** [comment]
You have to run it in command prompt, Do that by pressing ctrl+R, then cd to the dir, then put in node server.js

You can't click to run it.

**Comment by slossgaming** [comment]
You also have to download the programs from both websites, Download Node.JS, and Heroku command line thingy

**Comment by sentanos** [comment]
Duplicate of #40
