### ISSUE TITLE
HTTP 404 Not found/Server config error?

### ISSUE THREAD

**Issue by Avallex** [sentanos/roblox-js-server#45]
I know 404 is a common human error, but I've set up the server 3 times and followed the instructions exactly but I keep getting a 404 Error on roblox output. if I try to access the website directly myself this appears: 
![image](https://user-images.githubusercontent.com/30622420/28821239-9b3683e4-76ac-11e7-8283-8f5959f26555.png)
![image](https://user-images.githubusercontent.com/30622420/28821683-507eb9aa-76ae-11e7-9590-607fe8d377ce.png)
![image](https://user-images.githubusercontent.com/30622420/28821698-5da3be82-76ae-11e7-94ad-406269a86536.png)

Help would be appreciated as I'm trying to make this work for a struggling 112k member group :/
Thanks,
    Avallex

**Comment by Avallex** [comment]
Might seem that heroku is missing some sort of server settings?

**Comment by sentanos** [comment]
Make sure two step verification is not enabled on the account or the server will not be able to log in to the account and will error.

**Comment by Avallex** [comment]
Nope, two-factor auth is not enabled on heroku.

**Comment by sentanos** [comment]
I'm talking about the ROBLOX account.

**Comment by Avallex** [comment]
OH, yeah that is

**Comment by Avallex** [comment]
shit xD
