### ISSUE TITLE
Heroku Login

### ISSUE THREAD

**Issue by uJordy** [sentanos/roblox-js-server#51]
On the instructions it says to put in the 'username' and 'password' of the account you made in step 1 when you sign in by email. When I try to use my email instead of username it keeps saying  'bash: heroku: command not found'

**Comment by sentanos** [comment]
Uhh.. are you sure you installed heroku command line tools?

**Comment by uJordy** [comment]
I believe my path as incorrect it's now from Heroku to Heroku bin but now I'm getting this issue saying unexpected argument and then it shows my email because that's what I put in for my username; if that is correct that is

**Comment by uJordy** [comment]
![screenshot_2](https://user-images.githubusercontent.com/25880134/30059817-9f743f1c-9238-11e7-86df-d8d472abf17d.png)

**Comment by sentanos** [comment]
I didn't make it clear but it is assumed that you do `heroku login` _and then click enter_ before doing any of the other steps.

If you can't understand this you may not be suited for setting up these bots yourself. Although it is made for newbies, some amount of computer science background is assumed.

**Comment by uJordy** [comment]
I haven't done this language before, I've been doing python for computer science. But thank you

**Comment by uJordy** [comment]
I've changed my password and I'm not sure if It'll take some time for it to realise that I changed my password upon after putting in my details for heroku login. At the moment it's saying permission denied
