### ISSUE TITLE
im getting this error while trying to e.g. send a message to another player. help?

### ISSUE THREAD

**Issue by VoidedBlades** [sentanos/roblox-js-server#57]
![afbeelding](https://user-images.githubusercontent.com/26504790/32120416-bea8cf58-bb58-11e7-8fd4-6d62ba59a468.png)

**Comment by sentanos** [comment]
This error doesn’t mean anything. If you don’t show the code there is no way for me to know what the problem is.

**Comment by VoidedBlades** [comment]
my bad, i forgot to remove the http:// from the domain link, the curl error is gone but now i get a HTTP 502 (HTTP/1.1 502 Bad Gateway) error (i honestly don't know what this error means) so here's the code anyways just in case.

--module code:
https://github.com/sentanos/roblox-js-server/blob/master/lua/server.mod.lua

--calling the setrank function:

```
local server = require(script.Parent.Parent.Modules.PHPGroupManager)
local domain = 'floating-waters-52065.herokuapp.com/' -- Make sure there is no http:// in here!
local key = '/UAO9lTOYapr8ecV8cs/t3cP9c7na6rKHfRn7M6GDct+PdJyQJ40Jebe+CKZDgKV8TRLtbBqfhJc/eHNC7RHA8BCKkrFOkaIKC9/ripy34QzLq3m2qqy/GdyCg/5KHFUPbsuRNetr52ZP+6E2puKWrR9XvuAMG9bq+X02luwmID6aU7YBpq7sALl21Pv0OB4wy43VhuI3esN8w/Rl0ZC3LiJWwMv8PnwCKqgmq9L9UXLVBEPNJ9Plcv73+QqArHqiZ/qtrJO88='
local groupId = 3559695
local api = server(domain, key, groupId)

api.setRank(groupId, 47454179,2)

```

Edit: this is just the core for the problem, all the other lines of codes in the script are sensitive and i'd rather not to post those(leaking danger) also because they don't have to do anything with the problem.

**Comment by VoidedBlades** [comment]
got the error 502 fixed(saw some other issue on this exact subject) but now it has become a error 404...

**Comment by VoidedBlades** [comment]
the setup should be good now @sentanos as i've read in some other posts but it still keeps giving a error 404 and i cant quite figure out how to fix this error 404.

![afbeelding](https://user-images.githubusercontent.com/26504790/32126419-dea25938-bb70-11e7-8a2e-22fa90237090.png)

**Comment by sentanos** [comment]
This is not an error, it should say “Cannot GET /“ when you try to visit in the browser because it is not made for that but being accessed directly from the roblox server to do a specific action.

**Comment by VoidedBlades** [comment]
i get that this isn't an error but when i try to run it i get this problem on the developer console:

![afbeelding](https://user-images.githubusercontent.com/26504790/32132452-0f903152-bbc4-11e7-98f4-075569e2c2e8.png)

**Comment by sentanos** [comment]
Remove the last “/“ in the domain too exactly like the example shows

**Comment by VoidedBlades** [comment]
that worked thanks, now it says 
`ServerScriptService.Modules.PHPGroupManager:37: Incorrect authentication key` 

i have tried the key that already was in there (assumed it wasn't that) and my own key, both this message pop up

**Comment by sentanos** [comment]
Make sure they are exactly the same in the roblox script and the settings.json file, that’s the only thing that would cause this.

**Comment by VoidedBlades** [comment]
Thank you, this has been fixed rn i recreated it cause i lost the right key
