### ISSUE TITLE
Any way to do this on a web server?

### ISSUE THREAD

**Issue by SparkleOff** [sentanos/roblox-js-server#6]
Wanted to run it on a personal domain and my own web server.

**Comment by sentanos** [comment]
Of course, just remember to change the port in the script to 80 and install dependencies with "npm install" and there should be no problem running this regularly with the command "node server.js"

**Comment by SparkleOff** [comment]
@sentanos I have really tried doing that and i had no idea how it worked because the lua script bases it of, lets say for example "/setRank/'..group..'/'..userId..'/'..rank", and there is only the server.js

**Comment by sentanos** [comment]
Uh yeah... the server.js file handles that. If you have no idea what you are doing maybe you shouldn't be setting it up on your own server?

**Comment by SparkleOff** [comment]
@sentanos I have experience with a web server. I was running the php version but it got decreped and stopped working with my code. I have some experience in javascript but not a lot like building the respitory (sorry if i spelt that wrong) like heroku does.

**Comment by sentanos** [comment]
You obviously don't have experience with node.js though. Starting the server with "node server.js" does work, unlike PHP every path does not have to be a separate file, all the requests are handled manually by the server script instead of a backend such as apache.

**Comment by DevelopingCodes** [comment]
I'm gonna drop this here, don't know if it's any help:

https://devcenter.heroku.com/articles/custom-domains

**Comment by sentanos** [comment]
Close #6, this is not a real issue with the project.
