### ISSUE TITLE
Exile

### ISSUE THREAD

**Issue by mwalden2004** [sentanos/roblox-js-server#63]
Roblox-JS supports exile, add exile to request list.

**Comment by MrJesseh** [comment]
Yes, please add exile.  It would really help me out with my automated stuff.

**Comment by sentanos** [comment]
I never added exile because it is dangerous with a server that can be accessed by Roblox. If you need to exile please use [roblox-js](https://github.com/sentanos/roblox-js) (which has exile) and program an API to do what you need safely.

**Comment by mwalden2004** [comment]
Okay, Sure thing.
