### ISSUE TITLE
Heroku Login x509 error

### ISSUE THREAD

**Issue by DevelopingCodes** [sentanos/roblox-js-server#8]
To people who get the "Post https://api.heroku.com/login: x509: certificate signed by unknown authority" from the command "heroku login" should run the following command: "HEROKU_SSL_VERIFY=false heroku login"

Credits to source: https://imvishaltyagi444.wordpress.com/2016/02/24/heroku-certificate-signed-by-unknown-authority/

Just thought I should drop this here, not an issue.

**Comment by DevelopingCodes** [comment]
I do suggest that you ( @sentanos ) should explicitly state that in your heroku tutorial. ;)

**Comment by sentanos** [comment]
Interesting error but I have never received it myself and it definitely looks like a verification problem client-side. I recommend updating your own installed certificates and verifying your operating system installation but I will not put it in the official instructions unless it can be replicated by others.
