### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by slossgaming** [sentanos/roblox-js-server#9]
Exactly how can you execute this in PHP? I am attempting to use the message bot, but don't know what to do, Would you mind putting an example.

**Comment by slossgaming** [comment]
If you can please contact me via skype:matthewwalden11

**Comment by StateOfFirestone** [comment]
This is node.js, not PHP.

**Comment by sentanos** [comment]
Your lack of effort in even understanding what any of this is warrants exactly the same amount of effort in return (that is, none at all).

**Comment by slossgaming** [comment]
Your failing to understand me... I'm asking how can I use this in PHP? Meaning how may I execute it thru my code? I already have Heroku running it. I'm not dumb.

**Comment by sentanos** [comment]
I'm still failing to understand you
